kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: sybex/drone-kubectl
    tags:
      - latest
      - 0.${DRONE_BUILD_NUMBER}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: test
  image: sybex/drone-kubectl:0.${DRONE_BUILD_NUMBER}
  commands:
    - kubectl version | grep GitVersion
    - kubectl config get-contexts | grep default

- name: notify
  image: appleboy/drone-telegram
  when:
    status:
    - success
    - failure
  settings:
    token:
      from_secret: pipeline_bot
    to: 146910928
    message: >
      {{#success build.status}}
      Build [{{build.number}}]({{build.link}}) for {{repo.name}} succeeded. Good job.
      {{else}}
      Build [{{build.number}}]({{build.link}}) for {{repo.name}} failed. Fix me please.
      {{/success}}
