kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: sybex/drone-kubectl
    tags:
      - latest
      - 0.${DRONE_BUILD_NUMBER}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: security
  image: sybex/drone-clair
  detach: true
  settings:
    url:
      from_secret: clair_url
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    scan_image: sybex/drone-kubectl:0.${DRONE_BUILD_NUMBER}

- name: test
  image: sybex/drone-kubectl:0.${DRONE_BUILD_NUMBER}
  commands:
    - kubectl config get-contexts | grep default

- name: notify
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: pipeline_bot
    to: 146910928
    message: >
      {{#success build.status}}
      Build [{{build.number}}]({{build.link}}) for {{repo.name}} succeeded. Good job.
      {{else}}
      Build [{{build.number}}]({{build.link}}) for {{repo.name}} failed. Fix me please.
      {{/success}}
