#!/usr/bin/env bash

set -e

PATH="/opt/bin:$PATH"

INIT_FILE=/opt/sinlead/kubectl/initialized

if [ ! -f ${INIT_FILE} ]; then
    init-kubectl
    touch ${INIT_FILE}
fi

# Replace Drone build infos in deploymentfiles
for file in $(ls *yaml 2> /dev/null); do 
  cat $file | envsubst > $file.tmp
  mv $file.tmp $file
done

echo $@
kubectl $@
